# Generated by Django 5.2.7 on 2026-04-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0017_add_stock_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialPackPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='VICTNOW Trial Pack', max_length=100)),
                ('description', models.TextField(default='VICTNOW MUSE, VICTNOW NEXUS, VICTNOW FORGE - 5ML each')),
                ('price', models.DecimalField(decimal_places=2, default=999.0, help_text='Price in INR', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enable this price for trial pack')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trial Pack Price',
                'verbose_name_plural': 'Trial Pack Prices',
                'ordering': ['-created_at'],
            },
        ),
    ]
